### PR TITLE
Fix undefined macro _MSC_VER warning

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by ArashPartow** [comment]
@jschueller Thanks for the PR. Could you please tell me what versions of MSVC you are seeing this particular error/warning?  Also could please provide the exact _diagnostic_ that is produced by MSVC?

As I am able to build ExprTk error and warning free using W4 on the following versions of MSVC: 2005, 2010, 2015 and 2017

**Comment by jschueller** [comment]
I get this warning on Linux, on another machine than in the previous PR, I think it's latest clang (5.0.1), I dont have it right now to confirm (else it could be gcc 7.3).

**Comment by ArashPartow** [comment]
@jschueller  I've got the following bit of code, I can't seem to get the error you're describing:


    #include <cstdio>
    
    int main()
    {
       #if ABC_XYZ == 12345
          printf("Hello world\n");
       #endif
       return 0;
    }
    

- http://cpp.sh/46wia
- https://godbolt.org/g/7zGpzc
- http://rextester.com/GSRZ57808

**Comment by jschueller** [comment]
Even with "-Wundef" ?

**Comment by ArashPartow** [comment]
@jschueller  I guess my reply in that case would be the same as the shadow issue:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=49928


That being said, I'll make a note of it and look into resolving it in the next update as it's a minor issue.

**Comment by jschueller** [comment]
It's legit, I confirm it's clang, please reopen:

$ clang++ --version
clang version 5.0.1 (tags/RELEASE_501/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/sbin

$ cd /tmp && git clone https://github.com/ArashPartow/exprtk.git && cd exprtk && clang++ -Wundef exprtk_simple_example_01.cpp
Cloning into 'exprtk'...
In file included from exprtk_simple_example_01.cpp:22:
./exprtk.hpp:2783:26: warning: '_MSC_VER' is not defined, evaluates to 0 [-Wundef]
                     #if _MSC_VER == 1600
                         ^
1 warning generated.

**Comment by ArashPartow** [comment]
@jschueller  I've updated the tip. As it is now, that particular diagnostic should not appear.

**Comment by jschueller** [comment]
Thanks

**Pull request closed without merging**
