### PR TITLE
Fix warning: enum constant in boolean context [-Wint-in-bool-context]

### PR DESCRIPTION
**Pull request by saleyn**
Fix compiler warning

### CODE REVIEW

**Comment by saleyn** [comment]
For some reason you don't have "Issues" enabled for this repository, so I am raising it in this comment, which is actually unrelated to this PR.

I am getting this compilation error, and that code line doesn't quite make sense:
```c++
exprtk.hpp:24408:34: error: assignment of read-only member ‘exprtk::parser<double>::type_checker::default_return_type_’
[build] 24408 |             default_return_type_ = return_type;
[build]       |             ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
```

**Comment by ArashPartow** [comment]
Hello @saleyn

Thank-you for reporting this issue. This is a weird one. Completely agree this is a bug, but I'm still unable to get the compiler (g++10, clang++12, scan-build) to produce said diagnostic.

Currently using -Wall which should include "int-in-bool-context" or even explicitly including it doesn't raise the diagnostic.

The is the set of compiler params I'm using are:

    -pedantic-errors -Wall -Wextra -Werror -Wundef -std=c++20 -Wint-in-bool-context


Would you please be able to provide some more context on what it is you did to trigger the diagnostic?


----------------

In any case I decided to rework that entire bit of code as it was not up to scratch by any definition:

https://github.com/ArashPartow/exprtk/commit/22beb73856afab313ec3b7745453db8f1b2fad0b#diff-58c1983215ef11e39375e044aaa946c840e57c7f72d3ba9e303ee1a9b7cd9865R18056

**Comment by saleyn** [comment]
I believe this is fixed in the master.  Closing the request.

**Comment by ArashPartow** [comment]
@saleyn  if possible could you let me know how you found it?  

Would you be able to provide some more context on what it is you did to trigger the diagnostic?

**Comment by saleyn** [comment]
Here is a sample test case to reproduce it:
```
$ cat > t.cpp <<EOF
#include "exprtk.hpp"

namespace exprtk {
  template class symbol_table<double>;
}

int main()
{
}
EOF

$ c++ -pedantic-errors -Wall -Wextra -Werror -Wno-long-long -O1 -o t t.cpp -L/usr/lib -lstdc++ -lm
```

**Pull request closed without merging**
