### PR TITLE
Added support for functions with internal data.

### PR DESCRIPTION
**Pull request by gnudles**
Brief:
Let's say you want to add a function to the parser, which gives you
values from a specific array.
something like:
float values1[200]={...};
float values2[200]={...};
float values3[200]={...};
float getValue(void* v,float x)
{
	return ((float*)v)[(int)x%200];
}
int main()
{
	parser.add_function("values1",getValue,values1);
	parser.add_function("values2",getValue,values2);
	parser.add_function("values3",getValue,values3);
	float x;
	parser.add_variable("x",x);
	parser.parse("values1(x)*values2(x)");
}
........
I also added functors for functions like rand that doesn't get
arguments.

*********************************
I made those fixes for a plugin to the LMMS program.
I wanted to ask you, if I may embed exprtk.hpp into LMMS as GPL, because the LMMS project is GPL'd and it is not compatible with CPL.
https://github.com/LMMS/lmms/pull/3212

### CODE REVIEW

**Comment by ArashPartow** [comment]
From your use-case what it looks like you want to be doing is using just plain vectors. So add your external vectors (values1,values2,values3 etc) as vectors to a symbol_table then access the elements of the vector using indexes.


    float values1[200]={...};
    float values2[200]={...};
    float values3[200]={...};

    float x = 12;
    float y = 37;

    symbol_table_t symbol_table;
    symbol_table.add_variable("x"       ,       x);
    symbol_table.add_variable("y"       ,       y);
    symbol_table.add_vector  ("values1" , values1);
    symbol_table.add_vector  ("values2" , values2);
    symbol_table.add_vector  ("values3" , values3);

    expression_t expression;
    expression.register_symbol_table(symbol_table);

    std::string expression_string = "values1[x] * values2[2*y + 3]";

    parser_t parser;
    parser.compile(expression_string,expression);

    expression.value();


Some examples of using vectors:

https://github.com/ArashPartow/exprtk/blob/master/exprtk_test.cpp#L4215


If you're hell bent on using a function, then the igeneric_function is what you want, it's explained more in the documentation:

https://github.com/ArashPartow/exprtk/blob/master/readme.txt#L1659


You first need to define the igeneric_function like so:

    template <typename T>
    class get_value : public exprtk::igeneric_function<T>
    {
    public:

       typedef typename exprtk::igeneric_function<T> igfun_t;
       typedef typename igfun_t::parameter_list_t    parameter_list_t;
       typedef typename igfun_t::generic_type        generic_type;
       typedef typename generic_type::scalar_view    scalar_t;
       typedef typename generic_type::vector_view    vector_t;

       using exprtk::igeneric_function<T>::operator();

       randu()
       : exprtk::igeneric_function<T>("VT")
         /* VT - vector, index inside vector */
       {}

       inline T operator()(parameter_list_t parameters)
       {
          vector_t v(parameters[0]);

          std::size_t index = scalar_t(parameters[0])();

          return v[index % v.size()];
       }
    };



Then add the instance of 'get_value' to your symbol_table, and also add the external vectors (values1,values2,values3 etc) to the symbol_table as vectors, like so:

    float values1[200]={...};
    float values2[200]={...};
    float values3[200]={...};

    get_value<float> gv;

    symbol_table_t symbol_table;
    symbol_table.add_vector  ("values1" , values1);
    symbol_table.add_vector  ("values2" , values2);
    symbol_table.add_vector  ("values3" , values3);
    symbol_table.add_function("getvalue",      gv);

    expression_t expression;
    expression.register_symbol_table(symbol_table);

    std::string expression_string = "getvalue(values1,x) * getvalue(values2,x)";

    parser_t parser;
    parser.compile(expression_string,expression);

    expression.value();


I'd probably go with the first version as it's the more idiomatic way for dealing with vectors of scalars in ExprTk. More information on vectors can be found here:


https://github.com/ArashPartow/exprtk/blob/master/readme.txt#L1314

https://github.com/ArashPartow/exprtk/blob/master/readme.txt#L1204

**Comment by gnudles** [comment]
Thanks for your help, I really appreciate that, especially with the license issue.
How should I post the license change? 
Using vectors is not an option, because I'm performing interpolation on the values. And for the negative index values, I wrap them up (so -1 becomes size-1) and scale everything to [0,1] bounds:
float positiveFraction(float x)
{
	if (x<0)
	{
		x+=(int)(1-x);
	}
	return x-(int)(x);
}
The ifunction interface seems excellent, I'll move to it.
BTW, can function be optimized? like if the user types "x*user_func(14)" I expect that user_func(14) should not be evaluated on every x change.

**Comment by ArashPartow** [comment]
> Using vectors is not an option, because I'm performing interpolation on the values. 

It'd be great if could you show me an example of the kinds of calculations you're trying to perform, there may be a better way of _doing_ things...

For example have you had a chance to review the following:

http://www.partow.net/programming/exprtk/index.html#simpleexample13

-----

> How should I post the license change?

I can make the change and provide it to you , but could you let me know which one you prefer - will it be Boost or MIT?

-----

> BTW, can function be optimized? like if the user types "x*user_func(14)" I expect that user_func(14) should not be evaluated on every x change.

Yes that can be done in the constructor of the **ifunction** by explicitly noting that the function does not have side effects. The _'myfunc'_ ifunction in example Example 5 has that very property:

http://www.partow.net/programming/exprtk/index.html#simpleexample05

More detailed information can be found here:

https://github.com/ArashPartow/exprtk/blob/master/readme.txt#L1948

Your _'get_value'_ **ifunction** would now look like this:

    template <typename T>
    struct get_value : public exprtk::ifunction<T>
    {
       using exprtk::ifunction<T>::operator();
    
       get_value(float* v, std::size_t s)
       : exprtk::ifunction<T>(1),
         vec(v),
         size(s)
       { exprtk::disable_has_side_effects(*this); } // <------
    
       inline T operator()(const T& index)
       {
          return v[(int)index % size];
       }
    
       float* v;
       std::size_t size;
    };


In your example if _'user_func'_ is defined as having no side-effects the value of the sub-expression _'user_func(14)'_ will be determined at 'compile time' and then that value will be used every time the expression is evaluated.

Note, given that you're accessing a vector, the result of call will be based on whatever the values were in the vector at the **time of compilation**, not at the time of evaluation of the expression.

**Comment by gnudles** [comment]
Man, you are **genius**. thank you very much!
I you want to see my "wall of shame" you can watch this https://github.com/gnudles/lmms/blob/xpressive_plugin/plugins/xpressive/exprfront.cpp . I'm using the parser to generate sound...
I'm waiting for reply from LMMS team about the license.

**Comment by ArashPartow** [comment]
I did a quick review of the code and do have a couple of suggestions:

Initially C++ has a very powerful meta-programming facility, so whenever possible one should try to make use of it.

In the case of "freefunc1_optimized", if you were to add another template parameter called 'Functor' you can then proceed to specialize freefunc1_optimized not only on a numeric type (eg: float) but also on the specified functor (eg: square_wave).

The result of this change will be when invoking 'f(x)' the incurred inefficiency of pointer indirection will have been removed as the call to f will have been inlined at compile time. For more information have a read of the following:

https://en.wikibooks.org/wiki/Optimizing_C%2B%2B/Writing_efficient_code/Performance_improving_features#qsort_and_bsearch_functions


Here is how looks with the Functor update applied to your code:

    template <typename T, typename Functor>
    struct freefunc1_optimized : public exprtk::ifunction<T>
    {
       using exprtk::ifunction<T>::operator();

       freefunc1_optimized() : exprtk::ifunction<T>(1) {
          exprtk::disable_has_side_effects(*this);
       }

       inline T operator()(const T& x)
       { return Functor::process(x); }
    };


    struct sin_wave
    {
       static inline T process(float x) {
          x = positiveFraction(x);
          return sinf(x * F_2PI);
       }
    };

    static freefunc1_optimized<float,sin_wave> sin_wave_func;

The only requirement is a few extra lines per function in order to make it usable as a template parameter functor, which I think is a fair price to pay for the performance gains.

--------------

The next suggestion, given that the CMakelists in the root of the plugins directory enables C++11 mode, it would perhaps be a better option to use the C++11 random facilities.

**Comment by gnudles** [comment]
Hi,
I did what you said, except of the random vector implementation, because in order to retrieve a certain value, I have to use the discard method (in the random_engine class), and this method is O(N), not O(1) . the random vector has "infinite" cells and it can be random accessed. and I don't want to cache values.
Besides, it's used only to generate sound, and for this purpose it's good enough.
About the license, they said that both MIT (Expat) license and Boost license are fine.

**Comment by ArashPartow** [comment]
In your fork of lmms  [https://github.com/gnudles/lmms] where do plan on having exprtk.hpp?

Let me know and I'll make the license change on that as a PR.

**Comment by gnudles** [comment]
It's going to sit under "plugins/xpressive" (https://github.com/gnudles/lmms/tree/xpressive_plugin/plugins/xpressive). What's PR?
Thanks again

**Comment by ArashPartow** [comment]
A PR is a Pull Request.

Add it to that location, I'll clone your repo make the license change and then push it back as a PR, you can then merge it and we can then close this PR.

**Comment by gnudles** [comment]
Hi Arash,
Everything is ready.
https://github.com/gnudles/lmms/blob/xpressive_plugin/plugins/xpressive/exprtk.hpp
Thank's again.

**Comment by ArashPartow** [comment]
The PR is done and can be found here:  https://github.com/gnudles/lmms/pull/1

**Pull request closed without merging**
