### PR TITLE
Use cmake

### PR DESCRIPTION
**Pull request by spyridon97**
This is pull-request to incorporate cmake in the build, and installation process of the library.
The version of the library is extracted from the git tag.

### CODE REVIEW

**Comment by spyridon97** [comment]
There could be a problem with the circle ci, i am not sure if cmake is installed by default.

**Comment by luzpaz** [comment]
Any progress on this ?

**Comment by spyridon97** [comment]
The PR is ready to be merged. I am waiting on @ArashPartow .

**Comment by ArashPartow** [comment]
@spyridon97  Thank-you for the PR it's greatly appreciated!

I did some thinking about the external context usage of ExprTk as a third-party package, and what always comes to mind is the complex CMakeLists one typically sees that is an amalgamation of the library packing and the library's tests, benchmarks etc

So I thought perhaps a simpler approach is that for people that want to use ExprTk via cmake that the package should be specifically a simple single header only CMake package with nothing else included.

As such I've created the cmake branch and will update it in unison with the release branch. Currently there are three tags:

-  0.0.1-cmake
-  0.0.2-cmake
-  0.0.3-cmake

When you have a moment can you give this approach a go with `VTK `et al and if there's anything that needs changing or improving on that front we can work through them.

**Comment by spyridon97** [comment]
If you compare master with the cmake branch, it's clearly different. instead of having a branch for the cmake version, why not let both the makefile and the CMakelist.txt be available in master, so that people can choose what they prefer? People usually don't look into branches, so the cmake feature that many people want will be hidden.

**Comment by ArashPartow** [comment]
Just a quick note: Master in the context of ExprTk should not be considered release or prod ready. 

Master will move forward rapidly, it wont be as well tested and verified and there is not guarantee every commit in master will be in the release branch (which is the basis for the CMake branch). The idea being only after a large number of external testers are happy with a commit point and see no further issues, that point will be transferred to release the next tag generated and similarly the same with the cmake branch.

**Pull request closed without merging**
